# Generated by Django 4.2.9 on 2024-01-11 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_count', models.IntegerField()),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_views', to='advertiser_management.ad')),
            ],
        ),
        migrations.CreateModel(
            name='HourlyClicks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks_count', models.IntegerField()),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_clicks', to='advertiser_management.ad')),
            ],
        ),
    ]
