# Generated by Django 3.1.4 on 2024-01-02 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='advertiser',
            new_name='advertiser_id',
        ),
    ]
