# Generated by Django 3.1.4 on 2024-01-02 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0002_auto_20240102_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='advertiser_id',
            new_name='advertiser',
        ),
    ]
