# Generated by Django 3.1.4 on 2024-01-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0005_auto_20240103_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='click',
            old_name='view_datetime',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='view',
            old_name='view_datetime',
            new_name='datetime',
        ),
    ]
